---
abstract: 'Sound files of japanese words for use with L<Quiz::Flashcards>, includes only radicals'
author:
  - 'Christian Walde <mithaldu@yahoo.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Quiz::Flashcards: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.82'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Quiz-Flashcards-Audiobanks-Japanese_Words_Radicals
no_index:
  directory:
    - inc
    - share
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
